version: '6'
services:
  server:
    image: server4:v4
    build: .
    container_name: first
  proxy:
    image: nginx
    container_name: second
    volumes:
      - ./nginx2.conf:/etc/nginx/nginx.conf
    ports:
      - 80:8080